site_title = "ArxivDaily"
cache_max_days = 7
cache_url = "https://arxiv.alongwy.top/cache.json"

[[sources]]
limit = 1                               # Num Limit
category = "cs.CL"                      # Subject Category
title = "Computation and Language"      # Subject Title

[[sources]]
limit = 1
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 1
category = "cs.IR"
title = "Information Retrieval"

[[sources]]
limit = 1
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 1
category = "cs.MM"
title = "Multimedia"

[scripts]
